databases:
  - name: jobleet-db 
    databaseName: ${MYSQL_DATABASE}
    user: leetadmin
    password: ${MYSQL_PASSWORD}
    mysqlVersion: 8.0.3 

services:
  - type: pserv
    name: jobleet-api
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile 
    envVars:
      - key: DBHOST
        value: jobleet-db 
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
      - key: MYSQL_DATABASE
        value: ${MYSQL_DATABASE} 
      - key: MYSQL_PASSWORD
        value: ${MYSQL_PASSWORD}
    ports:
      - "8080"
