version: '3.8'

services:
  jobleet-database:
    image: postgres:13
    container_name: postgresql_server
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: leetadmin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "leetadmin", "-d", "${POSTGRES_DB}"]
      timeout: 20s
      retries: 10    
    
  jobleet-api:
    build: .
    depends_on:
      jobleet-database:
        condition: service_healthy
    ports: 
      - "8080:8080"
    restart: always
    environment:
      - DBHOST=jobleet-database
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  db_data:
