name: JobLeetCI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Server/JobLeet.WebApi

    - name: Build
      run: dotnet build --configuration Release Server/JobLeet.WebApi --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish Server/JobLeet.WebApi

    - name: Clean up
      run: dotnet clean Server/JobLeet.WebApi
